In [146]:
import numpy as np
import pandas as pd

In [147]:
import requests

In [148]:
from bs4 import  BeautifulSoup

In [175]:
url="https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

In [176]:
data=requests.get(url)
new_data=data.content

In [259]:
soup=BeautifulSoup(new_data,"html.parser")

In [266]:
company_name=soup.select("._4rR01T")
company=[]
for i in company_name:
#     print(i.contents[0])
    company.append(i.contents[0])

In [267]:
price_list=soup.select("._30jeq3")
price=[]
for i in price_list:
#     print(i.contents[0])
    price.append(i.contents[0])

In [278]:
review_list=soup.select("._3LWZlK")
review=[]
for i in review_list:
#     print(i.contents[0])
    review.append(i.contents[0])

In [279]:
review

['4.3',
 '4.3',
 '4.3',
 '4.1',
 '4.2',
 '4.1',
 '4.2',
 '4.2',
 '4.2',
 '4.3',
 '4.3',
 '4.3',
 '4.3',
 '4.3',
 '4.2',
 '4.4',
 '4.4',
 '4.4',
 '4.3',
 '4.3',
 '4.2',
 '4',
 '4.3',
 '4.2',
 '4.2',
 '4',
 '4',
 '4.4',
 '5',
 '1',
 '4.2',
 '3',
 '4',
 '4.1',
 '5',
 '5',
 '4.4',
 '5',
 '5']

In [280]:
import numpy as np

In [313]:
df=pd.DataFrame(np.array(company),columns=["company"])

In [314]:
df["price"]=price

In [315]:
len(company)

24

In [316]:
price=price[:24]

In [317]:
len(price)

24

In [318]:
len(review)

24

In [319]:
review=review[:24]

In [320]:
len(review)

24

In [321]:
df["review"]=review

In [322]:
df

                                       company    price review
0   SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)  ₹10,999    4.3
1   SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)  ₹10,999    4.3
2   SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  ₹10,999    4.3
3                 POCO C51 (Royal Blue, 64 GB)   ₹6,499    4.1
4      SAMSUNG Galaxy F04 (Jade Purple, 64 GB)   ₹7,099    4.2
5                POCO C51 (Power Black, 64 GB)   ₹6,499    4.1
6                 POCO C55 (Cool Blue, 128 GB)   ₹8,499    4.2
7                 POCO C50 (Royal Blue, 32 GB)   ₹5,499    4.2
8       SAMSUNG Galaxy F04 (Opal Green, 64 GB)   ₹7,099    4.2
9          Infinix SMART 7 (Azure Blue, 64 GB)   ₹6,999    4.3
10     Infinix SMART 7 (Emerald Green, 128 GB)   ₹7,599    4.3
11      Infinix SMART 7 (Emerald Green, 64 GB)   ₹6,999    4.3
12       Infinix SMART 7 (Night Black, 128 GB)   ₹7,599    4.3
13        Infinix SMART 7 (Azure Blue, 128 GB)   ₹7,599    4.3
14              POCO C55 (Power Black, 128 GB)   ₹8,499    4.2
15           vivo T2x 5G (Marine Blue, 128 GB)  ₹13,999    4.4
16           vivo T2x 5G (Aurora Gold, 128 GB)  ₹13,999    4.4
17           vivo T2x 5G (Aurora Gold, 128 GB)  ₹12,999    4.4
18         vivo T2x 5G (Glimmer Black, 128 GB)  ₹15,999    4.3
19           vivo T2x 5G (Marine Blue, 128 GB)  ₹15,999    4.3
20             POCO C55 (Forest Green, 128 GB)   ₹8,499    4.2
21          MOTOROLA e13 (Aurora Green, 64 GB)   ₹7,299      4
22        Infinix SMART 7 (Night Black, 64 GB)   ₹6,999    4.3
23             POCO C50 (Country Green, 32 GB)   ₹5,499    4.2

In [325]:
df["company_name"]=df["company"].str.split(" ",expand=True)[0]
df.head()

                                      company    price review company_name
0  SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)  ₹10,999    4.3      SAMSUNG
1  SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)  ₹10,999    4.3      SAMSUNG
2  SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  ₹10,999    4.3      SAMSUNG
3                POCO C51 (Royal Blue, 64 GB)   ₹6,499    4.1         POCO
4     SAMSUNG Galaxy F04 (Jade Purple, 64 GB)   ₹7,099    4.2      SAMSUNG

In [337]:
df

                                       company    price review company_name
0   SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)  ₹10,999    4.3      SAMSUNG
1   SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)  ₹10,999    4.3      SAMSUNG
2   SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  ₹10,999    4.3      SAMSUNG
3                 POCO C51 (Royal Blue, 64 GB)   ₹6,499    4.1         POCO
4      SAMSUNG Galaxy F04 (Jade Purple, 64 GB)   ₹7,099    4.2      SAMSUNG
5                POCO C51 (Power Black, 64 GB)   ₹6,499    4.1         POCO
6                 POCO C55 (Cool Blue, 128 GB)   ₹8,499    4.2         POCO
7                 POCO C50 (Royal Blue, 32 GB)   ₹5,499    4.2         POCO
8       SAMSUNG Galaxy F04 (Opal Green, 64 GB)   ₹7,099    4.2      SAMSUNG
9          Infinix SMART 7 (Azure Blue, 64 GB)   ₹6,999    4.3      Infinix
10     Infinix SMART 7 (Emerald Green, 128 GB)   ₹7,599    4.3      Infinix
11      Infinix SMART 7 (Emerald Green, 64 GB)   ₹6,999    4.3      Infinix
12       Infinix SMART 7 (Night Black, 128 GB)   ₹7,599    4.3      Infinix
13        Infinix SMART 7 (Azure Blue, 128 GB)   ₹7,599    4.3      Infinix
14              POCO C55 (Power Black, 128 GB)   ₹8,499    4.2         POCO
15           vivo T2x 5G (Marine Blue, 128 GB)  ₹13,999    4.4         vivo
16           vivo T2x 5G (Aurora Gold, 128 GB)  ₹13,999    4.4         vivo
17           vivo T2x 5G (Aurora Gold, 128 GB)  ₹12,999    4.4         vivo
18         vivo T2x 5G (Glimmer Black, 128 GB)  ₹15,999    4.3         vivo
19           vivo T2x 5G (Marine Blue, 128 GB)  ₹15,999    4.3         vivo
20             POCO C55 (Forest Green, 128 GB)   ₹8,499    4.2         POCO
21          MOTOROLA e13 (Aurora Green, 64 GB)   ₹7,299      4     MOTOROLA
22        Infinix SMART 7 (Night Black, 64 GB)   ₹6,999    4.3      Infinix
23             POCO C50 (Country Green, 32 GB)   ₹5,499    4.2         POCO